apiVersion: v1
kind: Pod
metadata:
  name: probes
  labels:
    app: do100-probes
  namespace: default
spec:
  containers:
    - name: probes
      image: 'quay.io/redhattraining/do100-probes:latest'
      ports:
        - containerPort: 8080