apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-03-05T11:03:09Z"
  generation: 1
  labels:
    app: do100-versioned-hello
  name: do100-versioned-hello
  namespace: default
  resourceVersion: "11729"
  uid: 731888df-2b86-418d-8501-26c57cf76e30
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: do100-versioned-hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: do100-versioned-hello
    spec:
      containers:
      - image: quay.io/redhattraining/do100-versioned-hello:v1.0
        imagePullPolicy: IfNotPresent
        name: do100-versioned-hello
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
